//@GeneratedCode
namespace QTProjectTeam.Logic.Controllers.App
{
    using System.Collections.Generic;
    using TEntity = Entities.App.Member;
    using TOutModel = Models.App.Member;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class MembersController : EntitiesController<TEntity, TOutModel>, Contracts.App.IMembersAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static MembersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        internal override IEnumerable<string> Includes => new string[] { nameof(TEntity.Projects) };
        ///
        /// Generated by the generator
        ///
        public MembersController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MembersController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
    }
}
