//@GeneratedCode
namespace QTProjectTeam.AspMvc
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTProjectTeam.Logic.Contracts.App.IMembersAccess<QTProjectTeam.Logic.Models.App.Member>, QTProjectTeam.Logic.Controllers.App.MembersController>();
            builder.Services.AddTransient<QTProjectTeam.Logic.Contracts.App.IProjectsAccess<QTProjectTeam.Logic.Models.App.Project>, QTProjectTeam.Logic.Controllers.App.ProjectsController>();
        }
    }
}
