//@GeneratedCode
namespace QTProjectTeam.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class MembersController : Controllers.GenericController<QTProjectTeam.Logic.Models.App.Member, QTProjectTeam.WebApi.Models.App.MemberEdit, QTProjectTeam.WebApi.Models.App.Member>
    {
        ///
        /// Generated by the generator
        ///
        static MembersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MembersController(QTProjectTeam.Logic.Contracts.App.IMembersAccess<QTProjectTeam.Logic.Models.App.Member> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTProjectTeam.WebApi.Models.App.Member ToOutModel(QTProjectTeam.Logic.Models.App.Member accessModel)
        {
            var handled = false;
            var result = default(QTProjectTeam.WebApi.Models.App.Member);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTProjectTeam.WebApi.Models.App.Member.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTProjectTeam.Logic.Models.App.Member accessModel, ref QTProjectTeam.WebApi.Models.App.Member? outModel, ref bool handled);
        partial void AfterToOutModel(QTProjectTeam.WebApi.Models.App.Member outModel);
    }
}
