//@GeneratedCode
namespace QTProjectTeam.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class MemberEdit
    {
        ///
        /// Generated by the generator
        ///
        static MemberEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MemberEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Name { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String Responsibilities { get; set; } = string.Empty;
    }
}
