//@GeneratedCode
namespace QTProjectTeam.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Project
    {
        ///
        /// Generated by the generator
        ///
        static Project()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Project()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String Designation { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String? Description { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTProjectTeam.WebApi.Models.App.Member> Members { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.WebApi.Models.App.Project Create()
        {
            BeforeCreate();
            var result = new QTProjectTeam.WebApi.Models.App.Project();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.WebApi.Models.App.Project Create(object other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.WebApi.Models.App.Project();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTProjectTeam.WebApi.Models.App.Project instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTProjectTeam.WebApi.Models.App.Project instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.WebApi.Models.App.Project Create(QTProjectTeam.Logic.Models.App.Project other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.WebApi.Models.App.Project();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTProjectTeam.Logic.Models.App.Project other);
        static partial void AfterCreate(QTProjectTeam.WebApi.Models.App.Project instance, QTProjectTeam.Logic.Models.App.Project other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTProjectTeam.Logic.Models.App.Project other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Designation = other.Designation;
                Description = other.Description;
                Members = other.Members.Select(e => QTProjectTeam.WebApi.Models.App.Member.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTProjectTeam.Logic.Models.App.Project other, ref bool handled);
        partial void AfterCopyProperties(QTProjectTeam.Logic.Models.App.Project other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTProjectTeam.WebApi.Models.App.Project other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Designation = other.Designation;
                Description = other.Description;
                Members = other.Members.Select(e => QTProjectTeam.WebApi.Models.App.Member.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTProjectTeam.WebApi.Models.App.Project other, ref bool handled);
        partial void AfterCopyProperties(QTProjectTeam.WebApi.Models.App.Project other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Project other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Designation, Description, Members, Id);
        }
    }
}
