//@GeneratedCode
namespace QTProjectTeam.Logic.Contracts.App
{
    ///
    /// Generated by the generator
    ///
    public partial interface IMembersAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
