//@GeneratedCode
namespace QTProjectTeam.Logic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Member
    {
        ///
        /// Generated by the generator
        ///
        static Member()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Member()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        
        new internal Entities.App.Member Source
        {
            get => (Entities.App.Member)(_source ??= new Entities.App.Member());
            set => _source = value;
        }
        
        public System.String Name
        {
            get => Source.Name;
            set => Source.Name = value;
        }
        
        public System.String Responsibilities
        {
            get => Source.Responsibilities;
            set => Source.Responsibilities = value;
        }
        
        public System.Collections.Generic.IList<QTProjectTeam.Logic.Models.App.Project> Projects
        {
            get => new CommonBase.Modules.Collection.DelegateList<QTProjectTeam.Logic.Entities.App.Project, QTProjectTeam.Logic.Models.App.Project>(Source.Projects);
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Member other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Responsibilities = other.Responsibilities;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Member other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Member other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTProjectTeam.Logic.Models.App.Member other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Responsibilities = other.Responsibilities;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTProjectTeam.Logic.Models.App.Member other, ref bool handled);
        partial void AfterCopyProperties(QTProjectTeam.Logic.Models.App.Member other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Member other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Name, Responsibilities, Projects, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Member Create()
        {
            BeforeCreate();
            var result = new QTProjectTeam.Logic.Models.App.Member();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Member Create(object other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Member();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Member Create(QTProjectTeam.Logic.Models.App.Member other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Member();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Member Create(Entities.App.Member other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Member();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Member instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Member instance, object other);
        static partial void BeforeCreate(QTProjectTeam.Logic.Models.App.Member other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Member instance, QTProjectTeam.Logic.Models.App.Member other);
        static partial void BeforeCreate(Entities.App.Member other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Member instance, Entities.App.Member other);
    }
}
