//@GeneratedCode
namespace QTProjectTeam.Logic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Project
    {
        ///
        /// Generated by the generator
        ///
        static Project()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Project()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        
        new internal Entities.App.Project Source
        {
            get => (Entities.App.Project)(_source ??= new Entities.App.Project());
            set => _source = value;
        }
        
        public System.String Designation
        {
            get => Source.Designation;
            set => Source.Designation = value;
        }
        
        public System.String? Description
        {
            get => Source.Description;
            set => Source.Description = value;
        }
        
        public System.Collections.Generic.IList<QTProjectTeam.Logic.Models.App.Member> Members
        {
            get => new CommonBase.Modules.Collection.DelegateList<QTProjectTeam.Logic.Entities.App.Member, QTProjectTeam.Logic.Models.App.Member>(Source.Members);
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Project other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Designation = other.Designation;
                Description = other.Description;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Project other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Project other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTProjectTeam.Logic.Models.App.Project other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Designation = other.Designation;
                Description = other.Description;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTProjectTeam.Logic.Models.App.Project other, ref bool handled);
        partial void AfterCopyProperties(QTProjectTeam.Logic.Models.App.Project other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Project other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Designation, Description, Members, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Project Create()
        {
            BeforeCreate();
            var result = new QTProjectTeam.Logic.Models.App.Project();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Project Create(object other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Project();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Project Create(QTProjectTeam.Logic.Models.App.Project other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Project();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTProjectTeam.Logic.Models.App.Project Create(Entities.App.Project other)
        {
            BeforeCreate(other);
            var result = new QTProjectTeam.Logic.Models.App.Project();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Project instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Project instance, object other);
        static partial void BeforeCreate(QTProjectTeam.Logic.Models.App.Project other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Project instance, QTProjectTeam.Logic.Models.App.Project other);
        static partial void BeforeCreate(Entities.App.Project other);
        static partial void AfterCreate(QTProjectTeam.Logic.Models.App.Project instance, Entities.App.Project other);
    }
}
