//@GeneratedCode
namespace QTProjectTeam.AspMvc.Controllers.App
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = QTProjectTeam.Logic.Models.App.Member;
    using TViewModel = QTProjectTeam.AspMvc.Models.App.Member;
    using TFilterModel = QTProjectTeam.AspMvc.Models.App.MemberFilter;
    using TAccessContract = QTProjectTeam.Logic.Contracts.App.IMembersAccess<QTProjectTeam.Logic.Models.App.Member>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class MembersController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static MembersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        protected override string ControllerName => "Members";
        ///
        /// Generated by the generator
        ///
        public MembersController(QTProjectTeam.Logic.Contracts.App.IMembersAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
